{"message":"<?php echo $this->message;?>","subtype":"<?php echo $this->subtype;?>","url":"<?php echo $this->url;?>","ctype":"<?php echo $this->ctype;?>","filename":"<?php echo $this->filename;?>","copied":"<?php echo $this->copied;?>","extracted":"<?php echo $this->extracted;?>","remoteexists":"<?php echo $this->remoteexists;?>","remotecreated":"<?php echo $this->remotecreated;?>","localupdated":"<?php echo $this->localupdated;?>"}

<pre>
<?php

print_r($this->copied);

?>
</pre>
